### ISSUE TITLE
右下键的目录索引有时在移动端无法跳转(pc网页端正常)

### ISSUE THREAD

**Issue by suzixin** [knightyun/knightyun.github.io#5]
可手机打开如下网页所示：
http://suzixin.cn/2021/07/30/dragonbook

**Comment by suzixin** [comment]
谢谢，这个问题解决了。

**Comment by suzixin** [comment]
http://suzixin.cn/2022/10/16/%E6%8A%95%E7%AF%AE

又复现了，这次是加入了视频的内容。

**Comment by knightyun** [comment]
> http://suzixin.cn/2022/10/16/%E6%8A%95%E7%AF%AE
> 
> 又复现了，这次是加入了视频的内容。

`<video width="100%">`
