### ISSUE TITLE
搜索框在提交博客后消失

### ISSUE THREAD

**Issue by suzixin** [knightyun/knightyun.github.io#6]
在批量提交post之后， 主页和post页面的搜索框都不见了。
提交中仅仅包含md文件，如下提交所示：
https://github.com/suzixin/suzixin.github.io/commit/be5c953b5dc99c7c7d7e5333e3b509d51b6f1888

**Comment by knightyun** [comment]
![image](https://user-images.githubusercontent.com/37565238/128627778-13ffaff2-915a-445c-a114-481769c55592.png)
 @suzixin 检查下，是你上传的文章有特殊符号导致 xml 解析错误，我只能修复让搜索框展示出来，解析错误的文章就无法被搜到了。

**Comment by suzixin** [comment]
感谢帮忙定位， 请问有方法可以查看是什么文章的特殊符号导致错误吗？

**Comment by knightyun** [comment]
> 感谢帮忙定位， 请问有方法可以查看是什么文章的特殊符号导致错误吗？

你注意看我上面截图的 url 和第二行报错信息
