### ISSUE TITLE
请问如何支持latex公式？

### ISSUE THREAD

**Issue by suzixin** [knightyun/knightyun.github.io#8]
例如：
`$$ E = mc^2 $$`

**Comment by knightyun** [comment]
参考链接：
> https://talk.jekyllrb.com/t/how-to-use-latex-on-jekyll/4119/2

-----------------------
1. `/_layouts/post.html` 添加如下代码：
```html
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
```
![image](https://user-images.githubusercontent.com/37565238/186627762-eee27641-f6b7-49c9-9118-7c45cbe3049c.png)

2. `.md` 文件中直接按 `Latex` 语法（`jekyll` 默认 markdown 解析器为 **`kramdown`**，其 `Latex` 引擎为 **`MathJax`**）书写内容：

![image](https://user-images.githubusercontent.com/37565238/186628338-cb90903d-0d27-46d9-a1a6-2c92ee527d18.png)

3. 更新web页面即可成功预览：
![image](https://user-images.githubusercontent.com/37565238/186628543-371e5eb1-30a4-410d-afa9-21cc766d7593.png)

@suzixin
